on:
    schedule:
      - cron: "0 9 */4 * *"  # A cada 4 dias às 9h da manhã
jobs:
    checkoutSupabase:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Supabase
          env: 
            SERVER_URL: ${{ secrets.SERVER_URL }}
          run: curl -X GET "$SERVER_URL/email/test@test.com"
  